### ISSUE TITLE
Version detection doesn't seem to work for some instances

### ISSUE THREAD

**Issue by nilesr** [Juerd/tootpick#3] opened 2022-11-30 08:58 UTC
Entering "ferretfrizz.biz" (which reports version 3.5.3) results in "That does not appear to be a Mastodon server."

**Comment by Juerd** [comment] 2022-11-30 18:39
Thanks. I have not been able to reproduce this issue (which was also reported by someone else (not on github)). When I enter that server domain, it works as intended.

Can you provide information about the request to /api/v1/instance as reported in the network tab of your browser's developer tools (F12)?

**Comment by Juerd** [comment] 2022-12-02 18:57
Probably fixed with c823060b. If not, please reopen.

**Closed as completed by Juerd** 2022-12-02 18:57 UTC
